### ISSUE TITLE
julian to pd.index

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/cadati#2]
Can we add [this function](https://github.com/TUW-GEO/pytesmo/blob/93412dd09b270b3b941d662f58a1acbdaf122728/src/pytesmo/timedate/julian.py#L43) from pytesmo to cadati?

Then the whole `pytesmo.timedate` module is integrated here.

Looks like the other [function](https://github.com/TUW-GEO/pytesmo/blob/93412dd09b270b3b941d662f58a1acbdaf122728/src/pytesmo/timedate/julian.py#L25) is already in here but under [a different name](https://github.com/TUW-GEO/cadati/blob/8c2b2b7a644076d0afa508c23e40c950d1dd27ce/src/cadati/jd_date.py#L302)

**Comment by sebhahn** [comment]
Both function are marked as `deprecated`. Should they still be used?

BTW a `numpy.datetime64` can be used as input for `pandas.DatatimeIndex`

Regarding `jd2doy`, I'd suggest to stick with the new name to be consistent within `cadati`. Code based on `pytesmo.timedate` needs to be changed in any case.

**Comment by wpreimes** [comment]
They are marked as deprecated because the are not used anymore in pytesmo. I also thought that all necessary functions are already here, but now I found a few places in other packages where `julian2datetimeindex` from pytesmo was used. So I was wondering if we wanted to move it here instead of only removing it.

As you said the function from pytesmo with the for-loop is bad anyway, and can be replaced by something like 
``` python
def julian2datetimeindex(jd, tz=pytz.UTC):
  return pd.DatetimeIndex(jd2dt(jd), tz=tz)
```

But should we add it, or not?

**Comment by sebhahn** [comment]
I wouldn't add it, I think it is fine to use `pd.DatetimeIndex(jd2dt(jd), tz=tz)` in the code directly (or `pd.DataFrame(data_dict, index=jd2dt(jd))`)
